### ISSUE TITLE
bower packages not installing

### ISSUE THREAD

**Issue by dentz** [benschwarz/sublime-bower#17]
Apologies in advance if I've made a rookie mistake, I believe node and npm are installed correctly on my machine.

I have installed Bower from within package control however the installation of bower packages is not working correctly. When i search for and locate a package then hit enter to install nothing seems to happen (no files are downloaded). 

This is what the console shows:
__
Traceback (most recent call last):
  File "./bower/commands/install.py", line 22, in get_file
AttributeError: 'InstallCommand' object has no attribute 'fileList'
__

Thanks for the help.

**Comment by benschwarz** [comment]
It's absolutely my fault! I accidentally broke the plugin for a whole ten minutes last night :-(

If you run package controls' update, it'll miraculously start working! 

On Fri, Apr 5, 2013 at 9:17 PM, dntz <notifications@github.com="mailto:notifications@github.com">> wrote:
Apologies in advance if I've made a rookie mistake, I believe node and npm are installed correctly on my machine.

I have installed Bower from within package control however the installation of bower packages is not working correctly. When i search for and locate a package then hit enter to install nothing seems to happen (no files are downloaded).

This is what the console shows:
__
Traceback (most recent call last):
File "./bower/commands/install.py", line 22, in get_file
AttributeError: 'InstallCommand' object has no attribute 'fileList'
__

Thanks for the help.

**Comment by dentz** [comment]
Thanks for the prompt response ben. Tried the package control update and nothing appears for the Bower package, also tried a uninstall/reinstall of the package with no luck either.

**Comment by syslap** [comment]
I'm having the same  issue, any solutions???

**Comment by benschwarz** [comment]
Guys, I think this should fix the plugin—so sorry its been broken for you. 
Package Control Upgrade Package — Bower, should get you the update.

**Comment by redhuntr** [comment]
Still not working. I tried everything.

**Comment by benschwarz** [comment]
@fernandoaguilar, can you please check your ST console and report any bower related errors you see? 
Did sublime text list a bower package when you went through the manual upgrade process?

**Comment by redhuntr** [comment]
The console show me this when I tried to install jquery (as your example):

Exception in thread Thread-22:
Traceback (most recent call last):
  File ".\threading.py", line 532, in __bootstrap_inner
  File ".\bower\utils\download.py", line 15, in run
  File ".\bower\utils\download.py", line 19, in install_package
  File ".\bower\utils\cli.py", line 35, in execute
NonCleanExitError: 7

Then when I upgrade (and yep, ST list a Bower package) manually and tried again, the consol show me the same.

Excuse my ignorance.

**Comment by benschwarz** [comment]
Fernando, absolutely no apology required. I'm a total newbie to sublime plugin authoring (and python!)  

As far as I can tell from your error report, it means that the underlying install command (which'll probably end has `bower install jquery --save`) is not working successfully.

Can you run `bower install jquery --save` in your Terminal and let me know how you go?

**Comment by benschwarz** [comment]
Can you all please verify now that:
- Bower works from the command line when you do `bower install jquery`
- Upgrade to the latest version

… If there are any errors remaining, please let me know here.

**Comment by dentz** [comment]
Update on my progress with getting this working.. still no luck.

No updates available within sublime, when i run 'bower install jquery' within terminal i get the following...

---

bower cloning git://github.com/components/jquery.git
bower cached git://github.com/components/jquery.git
bower fetching jquery
bower error status code of git: 127

There were errors, here's a summary of them:
jquery status code of git: 127

Thanks

**Comment by benschwarz** [comment]
@dntz - Are you on windows? Have you installed msysgit?

**Comment by benschwarz** [comment]
also, have you recently installed bower? are you using the latest version?

**Comment by dentz** [comment]
@benschwarz im on OS X 10.8.3 (don't think i have msysgit installed)

Yeah i installed bower last week so i presume it will be the latest version.

Thanks

**Comment by benschwarz** [comment]
Great, okay — msysgit is for Windows only (just checking, most people seem to miss that step)
What node version are you using? I know bower is currently broken with node 0.10.x.

**Comment by dentz** [comment]
Version v0.8.9, maybe an update will solve the issue, wasn't aware i was so far behind (its not something i use regularly).

Thanks

**Comment by benschwarz** [comment]
At the risk of 'passing the buck', maybe you should browse the bower issues list, or maybe log an issue there? I'm way out of my depth to know what to suggest now

**Comment by dentz** [comment]
I have updated node and re-installed bower, now when i try using the bower install package a downloading message appears in the bottom left of sublime, this disappears with no trace of files added to the document root and no error message in the console like before (nothing is added to the console). Is there any other way of checking whats happening here other than the console.

Thanks for the assistance.

P.S i get this when running jquery install within terminal...

 sudo bower install jquery.git

/usr/local/lib/node_modules/bower/node_modules/tmp/lib/tmp.js:219
    throw err;
          ^
TypeError: Arguments to path.join must be strings
    at path.js:365:15
    at Array.filter (native)
    at Object.exports.join (path.js:363:36)
    at Package.generateResourceId (/usr/local/lib/node_modules/bower/lib/core/package.js:812:23)
    at new Package (/usr/local/lib/node_modules/bower/lib/core/package.js:109:27)
    at null.<anonymous> (/usr/local/lib/node_modules/bower/lib/core/manager.js:129:16)
    at /usr/local/lib/node_modules/bower/node_modules/async/lib/async.js:99:13
    at Array.forEach (native)
    at _each (/usr/local/lib/node_modules/bower/node_modules/async/lib/async.js:32:24)
    at Object.async.each (/usr/local/lib/node_modules/bower/node_modules/async/lib/async.js:98:9)
