### ISSUE TITLE
Packages not installing on Windows - solution for documentation

### ISSUE THREAD

**Issue by DavidDeSloovere** [benschwarz/sublime-bower#20]
Something for the documentation / readme. I was about to give up, but I'm stubborn. Others might not be so stubborn.

I was having some problems using this on Windows. Turns out it's not your package and not npm, but Bower.

I hadn't used Bower before and just running `npm install -g bower` _wasn't enough_.
When trying out Bower in npm I got an error. From that I found that I had to install msysgit. I have some git stuff on my windows, but not msysgit.

So for Windows users I would suggest the following when sublime-bower is not working:
- run `bower install jquery` from npm
- If this returns "Error: spawn ENOENT" then Bower is not installed correctly

"To use Bower on Windows, you must install msysgit correctly."

**Comment by benschwarz** [comment]
When you say "correctly" @DavidDeSloovere, do you mean theres a certain option that you didn't tick the first time around? Or it just didn't work properly? 

Thanks so much for being stubborn! Now we can make this plugin better / actually work for everyone on Windows

**Comment by sindresorhus** [comment]
In the Bower readme: https://github.com/twitter/bower#a-note-for-windows-users

**Comment by benschwarz** [comment]
Hmm. So I could probably add to the sublime-bower readme asking that people install msysgit and link to #a-note-for-windows-users too.

**Comment by benschwarz** [comment]
Thanks for the report & help @DavidDeSloovere @sindresorhus !
