### ISSUE TITLE
API Error

### ISSUE THREAD

**Issue by ramiyahya** [benschwarz/sublime-bower#28]
I have installed NPM and Bower succesfully. I've ran a test bower install from terminal to check everything is working and it does.

But when I try bower install thru sublime, I get an API error message. Here's the console log 

error: Oh Snap! It looks like theres an error with the Bower API.
Traceback (most recent call last):
  File "./sublime_plugin.py", line 339, in run_
  File "./bower/commands/install.py", line 12, in run
  File "./bower/commands/install.py", line 17, in list_packages
AttributeError: 'NoneType' object has no attribute 'reverse'

What am I doing wrong?

**Comment by raphaelgoetter** [comment]
Hello.

I have the same error. 

(Win7 / Sublime Text 2 / nmp, git and bower installed and in PATH)

**Comment by benschwarz** [comment]
I haven't had time to get to this issue yet… its still in the bottom of my inbox :-1: 
If anyone else is able to check this out, it'd be great

**Comment by jensy** [comment]
:+1: I have the same issue.

**Comment by toropanov** [comment]
Oh Ben come on, the same issue for me too, I am really interested in this plugin, please up it in your inbox

**Comment by ebidel** [comment]
This cleared up the issue for me in Sublime 2 using Python 2.7.5. I'd check that it works for Python 3 and Sublime 3 permutations :)

**Comment by benschwarz** [comment]
I just pushed an update that fixes this issue (afaik). If you're still using this plugin, please do try again.

**Comment by raphaelgoetter** [comment]
YAY working on ST3 ! thanks

**Comment by ebidel** [comment]
Confirmed. Thanks.
