### ISSUE TITLE
Feature request: allow registry URL to be customized in user settings

### ISSUE THREAD

**Issue by timkendrick** [benschwarz/sublime-bower#33]
Great plugin! Is there any way the user could specify their own registry URL in the plugin settings?

Background: the company where I work uses a lot of internal modules which are stored in private repositories, so it'd be great if we could tell the Bower plugin to access our local fork of the [search-server](https://github.com/bower/search-server).

Would this be a lot of work? If you're too busy I can have a go at making a pull request – I'm no python expert though so can't guarantee how it would turn out!

**Comment by benschwarz** [comment]
I believe you could do this via a `.bowerrc` file in your project directory, @timkendrick

**Comment by timkendrick** [comment]
Maybe I'm doing something wrong in that case: I've already got a `.bowerrc` file in my project directory that specifies a custom `registry` URL but Sublime Bower doesn't seem to be picking it up.

If I open the terminal and `cd` to the project directory, commands like `bower search mylocalpackage` work fine and use the registry specified in `.bowerrc`. When I run the "Bower: Install" command from within Sublime, however, it loads the directory listing from `http://bower.herokuapp.com/` instead of the registry specified in `.bowerrc`.

It looks to me like the plugin never attempts to parse the project's `.bowerrc` file, seeing as the registry URL appears to be hard-coded to `"http://bower.herokuapp.com/"` in [bower/utils/api.py](https://github.com/benschwarz/sublime-bower/blob/master/bower/utils/api.py#L22-L23)

**Comment by timkendrick** [comment]
I've made a pull request which adds this feature. It'd be great if you could merge this into master!
