### ISSUE TITLE
Linux tests

### ISSUE THREAD

**Issue by tarciozemel** [benschwarz/sublime-bower#4]
Hi, nice plugin!

I'm with _Ubuntu 12.10 64bit_ here and seems like everything is fine and the installation occurs.

Just one thing: when I search for something, the list is populated with many occurences of the same package (even with the same repo address). I'm not a "bower guy", so I don't know if it's a bower thing or a sublime-bower thing.

**Comment by benschwarz** [comment]
Thanks for letting me know @tarciozemel, thats great news!
I've noticed a couple of double ups myself, I'll close this issue and open a new one to track any duplicates.
