### ISSUE TITLE
Duplicate packages seen in index

### ISSUE THREAD

**Issue by benschwarz** [benschwarz/sublime-bower#5]
Reference #4:

Reduce git sources / urls to ensure that only unique packages appear.

**Comment by benschwarz** [comment]
If anyone wants to post dupes that they're seeing here, I'll look into it from there.
As far as I'm concerned, any dupes that appear are because of an issue with the bower package list.

**Comment by Melindrea** [comment]
WordPress, Wordwrap, Wookmark-jquery and... more. In fact, for me (also Ubuntu 64 bit, 12.04) there almost appears to be up to 6 duplicates of every repository. 

(Also, great plugin, I will use it quite a bit)

**Comment by benschwarz** [comment]
Ok, I've figured it out. I'll issue a fix soon.

**Comment by Melindrea** [comment]
_thumbs up_
